run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - testdata
  max-issues-per-linter: 0
  max-same-issues: 0
